let gradeRowId=0;
function gradeDetails(){return Array.from($('gradeRows').children).map(row=>({semester:row.querySelector('[data-part="semester"]').value,subject:row.querySelector('[data-part="subject"]').value.trim(),credits:row.querySelector('[data-part="credits"]').value,grade:row.querySelector('[data-part="grade"]').value,achievement:row.querySelector('[data-part="achievement"]').value})).filter(r=>r.subject||r.credits||r.grade||r.achievement)}
function weightedGrade(rows){const counted=rows.filter(r=>r.subject&&Number.isInteger(Number(r.credits))&&Number(r.credits)>=1&&Number(r.credits)<=20&&Number.isInteger(Number(r.grade))&&Number(r.grade)>=1&&Number(r.grade)<=5);const credits=counted.reduce((s,r)=>s+Number(r.credits),0);return{count:counted.length,credits,average:credits?counted.reduce((s,r)=>s+Number(r.credits)*Number(r.grade),0)/credits:null}}
function updateGradeSummary(){const rows=gradeDetails(),v=weightedGrade(rows);$('gradeDetailCount').textContent=rows.length?' · '+rows.length+'과목 입력':'';$('gradeSummary').textContent=v.average===null?'등급과 이수학점을 입력하면 가중평균을 계산합니다.':'등급이 있는 '+v.count+'과목 · '+v.credits+'학점 · 입력 과목 가중평균 '+v.average.toFixed(2)+'등급 (5등급제)'}
function addGradeRow(){
 const n=++gradeRowId,row=node('div','','grade-row');row.dataset.gradeRow=String(n);
 function cell(part,label,control){const box=node('div',''),l=node('label',label);control.id='detail-'+part+'-'+n;control.dataset.part=part;l.htmlFor=control.id;control.setAttribute('aria-label',n+'번째 과목 '+label);box.append(l,control);row.append(box);return control}
 const semester=document.createElement('select');['1학년 1학기','1학년 2학기','2학년 1학기','2학년 2학기','3학년 1학기'].forEach(s=>{const o=node('option',s);o.value=s;semester.append(o)});cell('semester','학기',semester);
 const subject=document.createElement('input');subject.type='text';subject.maxLength=60;subject.placeholder='예: 수학Ⅰ';cell('subject','과목명',subject);
 const credit=document.createElement('input');credit.type='number';credit.min='1';credit.max='20';credit.step='1';credit.placeholder='학점';cell('credits','이수학점',credit);
 const grade=document.createElement('input');grade.type='number';grade.min='1';grade.max='5';grade.step='1';grade.placeholder='1~5';cell('grade','석차등급',grade);
 const achievement=document.createElement('select');['미입력','A','B','C','D','E'].forEach((s,i)=>{const o=node('option',s);o.value=i?s:'';achievement.append(o)});cell('achievement','성취도',achievement);
 const remove=node('button','삭제');remove.type='button';remove.setAttribute('aria-label',n+'번째 과목 삭제');remove.addEventListener('click',()=>{row.remove();updateGradeSummary()});row.append(remove);$('gradeRows').append(row);updateGradeSummary();return row;
}
function validateGradeDetails(){for(const row of $('gradeRows').children){const subject=row.querySelector('[data-part="subject"]'),credit=row.querySelector('[data-part="credits"]'),grade=row.querySelector('[data-part="grade"]'),achievement=row.querySelector('[data-part="achievement"]');if(!subject.value.trim()&&!credit.value&&!grade.value&&!achievement.value)continue;let target=null,message='';if(!subject.value.trim()){target=subject;message='세부 내신의 과목명을 입력하거나 빈 행을 삭제해주세요.'}else if(!credit.value||!credit.checkValidity()){target=credit;message='세부 내신의 이수학점은 1~20 사이 정수로 입력해주세요.'}else if(!grade.checkValidity()){target=grade;message='세부 내신의 석차등급은 1~5 사이 정수로 입력해주세요.'}if(target){$('gradeDetails').open=true;$('error').textContent=message;target.focus();return false}}return true}
$('addGrade').addEventListener('click',()=>{const row=addGradeRow();row.querySelector('[data-part="subject"]').focus()});
$('gradeRows').addEventListener('input',updateGradeSummary);$('gradeRows').addEventListener('change',updateGradeSummary);
