const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=__dirname,read=f=>fs.readFileSync(path.join(root,f),'utf8').replace(/\r\n/g,'\n'),db=JSON.parse(read('data.json')),ui=read('ui.js'),html=read('index.html');
const {linkApplications}=require('../../scripts/link-application-2027.cjs');
db.records=linkApplications(db.records,JSON.parse(fs.readFileSync(path.join(root,'..','..','data','application-2027.json'),'utf8')));
const known=db.records.filter(r=>r.status==='plan2028');
assert.equal(new Set(db.records.map(r=>r.id)).size,db.records.length);
assert.equal(known.length,47);assert.equal(new Set(known.map(r=>r.uni)).size,15);
for(const [uni,total] of [['한국공학대학교',120],['경일대학교',140],['한양대학교 ERICA',150],['가천대학교',260],['동의대학교',75],['순천향대학교',130],['유원대학교',120],['한국기술교육대학교',40]])assert.equal(known.filter(r=>r.uni===uni&&r.kind==='early').reduce((n,r)=>n+r.quota,0),total,uni+' 2028 plan total');
for(const r of db.records){assert.ok(typeof r.region==='string'&&r.region.length);assert.ok(r.sourceIds.length);r.sourceIds.forEach(k=>assert.ok(db.sources[k]));assert.equal(r.schoolTypeEvidence,'unknown');if(r.status==='plan2028'){assert.equal(r.year,2028);assert.ok(r.sourceIds.every(k=>db.sources[k].year===2028));assert.ok((Number.isInteger(r.quota)&&r.quota>0)||(r.quota===null&&r.sourceIds.includes('jnu')&&r.quotaNote.includes('전체 90명')))}else{assert.equal(r.quota,null);assert.equal(r.graduateEligible,null)}r.history.forEach(h=>{assert.ok(h.year<2028);assert.equal(h.schoolType,'unknown')});}
assert.equal(known.filter(r=>r.uni==='선문대학교').reduce((n,r)=>n+r.quota,0),90);
assert.equal(known.filter(r=>r.uni==='백석대학교').reduce((n,r)=>n+r.quota,0),90);
assert.equal(known.filter(r=>r.uni==='전남대학교'&&r.quota===null).length,4);
const c={DB:db,URL,document:{},Set};vm.createContext(c);vm.runInContext(ui.replace(/init\(\);\s*$/,''),c);
const base={query:'',field:'',region:'',kind:'',work:'',evaluation:'',resultSchool:'',graduate:true,noMinimum:false,references:false,dorm:false};
const search=p=>db.records.filter(r=>c.matches(r,{...base,...p}));
assert.equal(search({}).length,46);assert.equal(search({evaluation:'sincerity'}).length,4);assert.ok(search({evaluation:'interview'}).every(r=>r.interviewWeight>=50));assert.equal(search({region:'부산'}).length,3);assert.equal(search({resultSchool:'general'}).length,0);assert.equal(search({resultSchool:'science'}).length,0);assert.equal(search({kind:'worker'}).length,0);assert.equal(search({kind:'worker',graduate:false}).length,1);assert.equal(search({work:'no'}).length,16);assert.equal(search({graduate:false,references:true}).length,61);assert.equal(search({dorm:true}).length,46);assert.equal(vm.runInContext("safeUrl('javascript:alert(1)')",c),null);
assert.ok(html.includes(ui));assert.ok(html.includes("connect-src 'none'"));assert.ok(!/localStorage|sessionStorage|indexedDB|sendBeacon|fetch\(|XMLHttpRequest|WebSocket/.test(html));new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
const histories=db.records.flatMap(r=>r.history);
const ssu=db.records.find(r=>r.id==='contract-007');
assert.equal(ssu.quota,8);assert.equal(ssu.history[0].cut70,2.55);assert.equal(ssu.history[0].competitionRatio,15.8);assert.match(ssu.method,/3배수/);
for(const [id,total] of [['contract-001',28],['contract-002',20],['contract-003',30]]){const r=db.records.find(r=>r.id===id);assert.equal(r.tracks.reduce((n,t)=>n+t.quota,0),total);assert.equal(r.track,'계열적합전형');assert.equal(r.minimum,'none');assert.match(r.tracks[1].method,/4개 합 9/);assert.match(r.support,/2027 참고/)}
assert.equal(db.records.filter(r=>r.history.length).length,14);assert.equal(histories.length,16);
assert.equal(histories.filter(h=>h.sourceType==='official').length,10);
assert.equal(histories.filter(h=>Number.isFinite(h.competitionRatio)).length,10);
for(const h of histories){assert.ok(Number.isFinite(h.cut70)||Number.isFinite(h.gradeMean));for(const key of ['cut50','cut70','gradeMean'])if(h[key]!=null)assert.ok(h[key]>=1&&h[key]<=9);if(h.sourceType==='official'){assert.match(h.sourceSha256,/^[a-f0-9]{64}$/);assert.ok(h.sourceLocation);assert.equal(h.year,2026);assert.ok(h.note)}}
const g=db.records.find(r=>r.uni==='가천대학교'&&r.major==='게임·영상학과').history[0];assert.equal(g.cut70,4.95);assert.equal(g.competitionRatio,25.67);
const t=db.records.find(r=>r.uni==='한국공학대학교'&&r.major==='IT융합디자인공학과').history[0];assert.equal(t.gradeMean,5.1);assert.equal(t.cut70,undefined);assert.equal(c.historyMetric(t),'평균 5.10등급');assert.equal(c.historyMetric(g),'70% 컷 4.95등급');assert.equal(c.historyText({history:[]} ),'-');assert.equal(c.competitionText({}),'-');assert.equal(c.competitionText(g),'25.67:1');
const samples=[{id:'b',uni:'나',major:'학과',quota:10,history:[{year:2026,cut70:2,competitionRatio:10}]},{id:'a',uni:'가',major:'학과',quota:2,history:[{year:2025,cut70:1,competitionRatio:20},{year:2026,cut70:4,competitionRatio:2}]},{id:'m',uni:'다',major:'학과',quota:4,history:[{year:2026,gradeMean:1}]},{id:'z',uni:'라',major:'학과',quota:null,history:[]}];
const order=(key,dir)=>samples.slice().sort((a,b)=>c.compareRows(a,b,key,dir)).map(r=>r.id).join(',');
samples[0].application2027={year:2027,status:'final',ratio:10,recruitment:8};samples[1].application2027={year:2027,status:'final',ratio:2,recruitment:6};
assert.equal(order('quota',1),'a,m,b,z');assert.equal(order('quota',-1),'b,m,a,z');
assert.equal(order('competition',1),'a,b,m,z');assert.equal(order('competition',-1),'b,a,m,z');
assert.equal(order('history',1),'b,a,m,z');assert.equal(order('history',-1),'a,b,m,z');
assert.equal(order('uni',1),'a,b,m,z');assert.equal(order('uni',-1),'z,m,b,a');
assert.equal(db.records.filter(r=>c.currentApplications(r).length).length,37);
assert.equal(new Set(db.records.filter(r=>c.currentApplications(r).length).map(r=>r.uni)).size,13);
assert.ok(db.records.filter(r=>r.application2027).every(r=>r.application2027.year===2027&&r.application2027.status==='final'));
assert.equal(ssu.application2027.ratio,18.38);assert.equal(ssu.application2027.recruitment,8);assert.equal(ssu.history[0].competitionRatio,15.8);
assert.equal(c.history2026({history:[{year:2025,cut70:1},{year:2026,gradeMean:2}]}).length,0);
assert.equal(c.currentApplications({history:[{year:2026,competitionRatio:10}]}).length,0);
assert.equal(c.currentApplications({application2027:{year:2026,status:'final',ratio:10}}).length,0);
assert.equal(order('recruitment2027',1),'a,b,m,z');assert.equal(order('recruitment2027',-1),'b,a,m,z');
const kyungil=db.records.filter(r=>r.uni==='경일대학교'&&r.kind==='early');
assert.equal(kyungil.length,4);assert.ok(kyungil.every(r=>c.currentApplications(r).length===2));
const factory=kyungil.find(r=>r.major==='스마트팩토리공학부');
assert.equal(c.currentApplications(factory).map(h=>h.ratio).join(','),'3.93,1.9');
assert.equal(c.sortValue(factory,'competition'),3.93);
const rawFactory={...factory};delete rawFactory.application2027Options;
const apps=JSON.parse(fs.readFileSync(path.join(root,'../../data/application-2027.json'),'utf8'));
const chosen=c.currentApplications(factory)[0];
assert.equal(linkApplications([rawFactory],{...apps,records:[...apps.records,chosen]})[0].application2027Options,undefined);
assert.equal(c.currentApplications(db.records.find(r=>r.uni==='유원대학교'&&r.major==='문화복지학과'))[0].ratio,0);
const sch=c.currentApplications(db.records.find(r=>r.uni==='순천향대학교'))[0];
assert.equal(sch.recruitment,130);assert.equal(sch.applicants,254);assert.equal(sch.ratio,1.95);assert.equal(sch.sourceRow,72);
assert.ok(db.records.filter(r=>r.uni==='선문대학교'||r.uni==='동의대학교').every(r=>!c.currentApplications(r).length));
console.log('PASS contracts: 47 current / 14 reference, 8 early-program quota totals, qualification/work/school-type filters, sources, privacy and syntax');
